#!/usr/bin/env python
import os
import sys

try:
    here = __file__
except NameError:
    # Python 2.2
    here = sys.argv[0]

relative_paste = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(here))), 'paste')

if os.path.exists(relative_paste):
    sys.path.insert(0, os.path.dirname(relative_paste))
import paste.app_setup
print paste.app_setup.__file__

from paste import app_setup
sys.exit(app_setup.run(sys.argv))
