#!/usr/bin/env python
import os
import sys

try:
    here = __file__
except NameError:
    # Python 2.2
    here = sys.argv[0]

relative_wsgikit = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(here))), 'wsgikit')


if os.path.exists(relative_wsgikit):
    sys.path.insert(0, os.path.dirname(relative_wsgikit))

from wsgikit import server
sys.exit(server.run_commandline(sys.argv[1:]))
